### ISSUE TITLE
Activate HTTPS + Enforce HTTPS

### ISSUE THREAD

**Issue by cfoellmann** [code9media/overthecs.github.io#72]
You should activate HTTPS for the custom domain in the GitHub pages settings.
SEE: https://help.github.com/en/articles/about-custom-domains-and-github-pages

And enforce HTTPS 

SEE: https://help.github.com/en/articles/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by s1099** [comment]
The Website is using HTTPS as on 2 July 2020,
